#!/usr/bin/env php

<?php
/**
 * @copyright   2019 - Vindite
 * @author      Vinicius Oliveira <vinicius_o.a@live.com>
 * @category    Micro Framework
 * @since       2019-10-17
 */

require_once "vendor/autoload.php";

use Symfony\Component\Console\Application;
use Selene\Console;

class Solvr
{
    /**
     * Define the application path dir
     */
    const APP_ROOT_PATH = __DIR__.DIRECTORY_SEPARATOR."App";

    /**
     * Define Symfony Application Object
     *
     * @var Application
     */
    protected $application;

    /**
     * Define Commands Object
     *
     * @var Command
     */
    protected $commands;

    /**
     * Execute console commands
     *
     * @return void
     */
    public function run() : void
    {
        $this->getApplication()->addCommands($this->getCommands()->getSolvrCommands());
        $this->getApplication()->run();
    }

    /**
     * Instantiate Symfone Application Console
     *
     * @return Application
     */
    protected function getApplication() : Application
    {
        if (!isset($this->application)) {
            $this->application = new Application;
        }

        return $this->application;
    }

    /**
     * Instantiate Solvr Console
     *
     * @return Solvr
     */
    protected function getCommands() : Console\Solvr
    {
        if (!isset($this->commands)) {
            $this->commands = new Console\Solvr(self::APP_ROOT_PATH);
        }

        return $this->commands;
    }
}

(new Solvr)->run();